### ISSUE TITLE
bug: claiming fractions from allowlist silent fail

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#240]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

1. I used my testnet wallet address to create a hypercert for a project that I was eligible to claim (from my social wallet)
2. The dashboard prompted me to claim as expected
3. I was unable to sign the transaction; the interaction stalled out

### Describe the Bug

The interaction stalled out determining [the proofs](https://bafkreibopocbif4zpbfcezoeugjykhf2sk7yp77tnmvyic4ofvsriq2vxe.ipfs.nftstorage.link/)
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/42869436/218236753-6e2ea28c-d4dd-48fd-81ea-b323408867e9.png">

Also seeing a 404
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/42869436/218236783-1b8633ab-9664-49a9-a9ca-8714ac745ccf.png">

### Expected Behavior

I should be able to claim my fractions and have them show up in my dashboard

**Comment by ccerv1** [comment]
Recreated this issue again just now.  I had four fractions that I was eligible to claim at the time.

It silent fails at Step 2.
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/42869436/218450494-1edffad3-f944-4b0c-9ee5-2bdd8bf6bb32.png">

The first error links to a [404 on Vercel](https://hypercerts.vercel.app/_next/data/PDs6aqcT6dOjpgf_mC96D/docs.json?catchall=docs) 

The second error apparently fails on [this call](https://hypercerts.vercel.app/_next/static/chunks/8-2adad64030caa55b.js) 

Here is the console log:

```
/_next/data/PDs6aqcT6dOjpgf_mC96D/docs.json?catchall=docs:1          Failed to load resource: the server responded with a status of 404 ()
386-587252f7e98a22d6.js:239 Getting metadata bafybeiddrcassx2bdts447yjujmgyzoyuni4rjxksofc5lo4ytypnjbiuu at https://nftstorage.link/ipfs/bafybeiddrcassx2bdts447yjujmgyzoyuni4rjxksofc5lo4ytypnjbiuu
8-2adad64030caa55b.js:1 Metadata bafybeiddrcassx2bdts447yjujmgyzoyuni4rjxksofc5lo4ytypnjbiuu:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 Claim 0x94a04ce2e537eaf2bdabd629de503797e7021e87-16673835979125984709705355764156642361344:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 Claim 0x94a04ce2e537eaf2bdabd629de503797e7021e87-17014118346046923173168730371588410572800:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 Claim 0x94a04ce2e537eaf2bdabd629de503797e7021e87-12930729942995661611608235082407192035328:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 Claim 0x94a04ce2e537eaf2bdabd629de503797e7021e87-15312706511442230855851857334429569515520:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 ClaimTokens 0x94a04ce2e537eaf2bdabd629de503797e7021e87-16673835979125984709705355764156642361344:
8-2adad64030caa55b.js:1 Array(0)
386-587252f7e98a22d6.js:239 Getting metadata bafkreibnn2ca3jrrj35omkafliiuiotrh7rcppcno2sukoqkrcc7yq3asy at https://nftstorage.link/ipfs/bafkreibnn2ca3jrrj35omkafliiuiotrh7rcppcno2sukoqkrcc7yq3asy
8-2adad64030caa55b.js:1 ClaimTokens 0x94a04ce2e537eaf2bdabd629de503797e7021e87-17014118346046923173168730371588410572800:
8-2adad64030caa55b.js:1 Array(0)
386-587252f7e98a22d6.js:239 Getting metadata bafkreigzstb2f2fxr4oktwxm4kda5y4lfh3u5d2lcbjoh6ns5y7jqnydtu at https://nftstorage.link/ipfs/bafkreigzstb2f2fxr4oktwxm4kda5y4lfh3u5d2lcbjoh6ns5y7jqnydtu
8-2adad64030caa55b.js:1 ClaimTokens 0x94a04ce2e537eaf2bdabd629de503797e7021e87-12930729942995661611608235082407192035328:
8-2adad64030caa55b.js:1 Array(0)
386-587252f7e98a22d6.js:239 Getting metadata bafkreifaldzl5eqsfjofm6twz4v3eahc54lcsuabz6i7ekjxcgycswffki at https://nftstorage.link/ipfs/bafkreifaldzl5eqsfjofm6twz4v3eahc54lcsuabz6i7ekjxcgycswffki
8-2adad64030caa55b.js:1 Metadata bafkreifaldzl5eqsfjofm6twz4v3eahc54lcsuabz6i7ekjxcgycswffki:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 ClaimTokens 0x94a04ce2e537eaf2bdabd629de503797e7021e87-15312706511442230855851857334429569515520:
8-2adad64030caa55b.js:1 Array(0)
386-587252f7e98a22d6.js:239 Getting metadata bafybeie2zhhifyhsffzfo476ipsyz4h4vtpm5iszqwbwzk6miucmcufuke at https://nftstorage.link/ipfs/bafybeie2zhhifyhsffzfo476ipsyz4h4vtpm5iszqwbwzk6miucmcufuke
8-2adad64030caa55b.js:1 Metadata bafkreigzstb2f2fxr4oktwxm4kda5y4lfh3u5d2lcbjoh6ns5y7jqnydtu:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 Metadata bafybeie2zhhifyhsffzfo476ipsyz4h4vtpm5iszqwbwzk6miucmcufuke:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 Metadata bafkreibnn2ca3jrrj35omkafliiuiotrh7rcppcno2sukoqkrcc7yq3asy:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 Claim 0x94a04ce2e537eaf2bdabd629de503797e7021e87-17014118346046923173168730371588410572800:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 ClaimTokens 0x94a04ce2e537eaf2bdabd629de503797e7021e87-17014118346046923173168730371588410572800:
8-2adad64030caa55b.js:1 Array(0)
386-587252f7e98a22d6.js:239 Getting metadata bafkreigzstb2f2fxr4oktwxm4kda5y4lfh3u5d2lcbjoh6ns5y7jqnydtu at https://nftstorage.link/ipfs/bafkreigzstb2f2fxr4oktwxm4kda5y4lfh3u5d2lcbjoh6ns5y7jqnydtu
8-2adad64030caa55b.js:1 Metadata bafkreigzstb2f2fxr4oktwxm4kda5y4lfh3u5d2lcbjoh6ns5y7jqnydtu:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 Claim 0x94a04ce2e537eaf2bdabd629de503797e7021e87-17014118346046923173168730371588410572800:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 Claim 0x94a04ce2e537eaf2bdabd629de503797e7021e87-16673835979125984709705355764156642361344:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 Claim 0x94a04ce2e537eaf2bdabd629de503797e7021e87-15312706511442230855851857334429569515520:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 Claim 0x94a04ce2e537eaf2bdabd629de503797e7021e87-12930729942995661611608235082407192035328:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 ClaimTokens 0x94a04ce2e537eaf2bdabd629de503797e7021e87-17014118346046923173168730371588410572800:
8-2adad64030caa55b.js:1 Array(0)
386-587252f7e98a22d6.js:239 Getting metadata bafkreigzstb2f2fxr4oktwxm4kda5y4lfh3u5d2lcbjoh6ns5y7jqnydtu at https://nftstorage.link/ipfs/bafkreigzstb2f2fxr4oktwxm4kda5y4lfh3u5d2lcbjoh6ns5y7jqnydtu
8-2adad64030caa55b.js:1 ClaimTokens 0x94a04ce2e537eaf2bdabd629de503797e7021e87-15312706511442230855851857334429569515520:
8-2adad64030caa55b.js:1 Array(0)
386-587252f7e98a22d6.js:239 Getting metadata bafybeie2zhhifyhsffzfo476ipsyz4h4vtpm5iszqwbwzk6miucmcufuke at https://nftstorage.link/ipfs/bafybeie2zhhifyhsffzfo476ipsyz4h4vtpm5iszqwbwzk6miucmcufuke
8-2adad64030caa55b.js:1 ClaimTokens 0x94a04ce2e537eaf2bdabd629de503797e7021e87-16673835979125984709705355764156642361344:
8-2adad64030caa55b.js:1 Array(0)
386-587252f7e98a22d6.js:239 Getting metadata bafkreibnn2ca3jrrj35omkafliiuiotrh7rcppcno2sukoqkrcc7yq3asy at https://nftstorage.link/ipfs/bafkreibnn2ca3jrrj35omkafliiuiotrh7rcppcno2sukoqkrcc7yq3asy
8-2adad64030caa55b.js:1 Metadata bafkreigzstb2f2fxr4oktwxm4kda5y4lfh3u5d2lcbjoh6ns5y7jqnydtu:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 Metadata bafybeie2zhhifyhsffzfo476ipsyz4h4vtpm5iszqwbwzk6miucmcufuke:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 Metadata bafkreibnn2ca3jrrj35omkafliiuiotrh7rcppcno2sukoqkrcc7yq3asy:
8-2adad64030caa55b.js:1 Object
8-2adad64030caa55b.js:1 ClaimTokens 0x94a04ce2e537eaf2bdabd629de503797e7021e87-12930729942995661611608235082407192035328:
8-2adad64030caa55b.js:1 Array(0)
386-587252f7e98a22d6.js:239 Getting metadata bafkreifaldzl5eqsfjofm6twz4v3eahc54lcsuabz6i7ekjxcgycswffki at https://nftstorage.link/ipfs/bafkreifaldzl5eqsfjofm6twz4v3eahc54lcsuabz6i7ekjxcgycswffki
8-2adad64030caa55b.js:1 Metadata bafkreifaldzl5eqsfjofm6twz4v3eahc54lcsuabz6i7ekjxcgycswffki:
8-2adad64030caa55b.js:1 Object
386-587252f7e98a22d6.js:239 Getting metadata bafkreifaldzl5eqsfjofm6twz4v3eahc54lcsuabz6i7ekjxcgycswffki at https://nftstorage.link/ipfs/bafkreifaldzl5eqsfjofm6twz4v3eahc54lcsuabz6i7ekjxcgycswffki
386-587252f7e98a22d6.js:239 Getting  data bafkreibopocbif4zpbfcezoeugjykhf2sk7yp77tnmvyic4ofvsriq2vxe at https://nftstorage.link/ipfs/bafkreibopocbif4zpbfcezoeugjykhf2sk7yp77tnmvyic4ofvsriq2vxe
386-587252f7e98a22d6.js:239 Getting metadata bafybeie2zhhifyhsffzfo476ipsyz4h4vtpm5iszqwbwzk6miucmcufuke at https://nftstorage.link/ipfs/bafybeie2zhhifyhsffzfo476ipsyz4h4vtpm5iszqwbwzk6miucmcufuke
386-587252f7e98a22d6.js:239 Getting metadata bafkreigzstb2f2fxr4oktwxm4kda5y4lfh3u5d2lcbjoh6ns5y7jqnydtu at https://nftstorage.link/ipfs/bafkreigzstb2f2fxr4oktwxm4kda5y4lfh3u5d2lcbjoh6ns5y7jqnydtu
386-587252f7e98a22d6.js:239 Getting  data bafkreiebw6za7ihx4pmz3cwvmifzcrekepn4qbktrzdp646zexnmz2utke at https://nftstorage.link/ipfs/bafkreiebw6za7ihx4pmz3cwvmifzcrekepn4qbktrzdp646zexnmz2utke
386-587252f7e98a22d6.js:239 Getting metadata bafkreibnn2ca3jrrj35omkafliiuiotrh7rcppcno2sukoqkrcc7yq3asy at https://nftstorage.link/ipfs/bafkreibnn2ca3jrrj35omkafliiuiotrh7rcppcno2sukoqkrcc7yq3asy
386-587252f7e98a22d6.js:239 Getting  data bafkreififivsopyagq55ddc6ixsqjsylryzoal7ran7vjjtewmp3xti75i at https://nftstorage.link/ipfs/bafkreififivsopyagq55ddc6ixsqjsylryzoal7ran7vjjtewmp3xti75i
386-587252f7e98a22d6.js:239 Getting  data bafkreib4hdjyxss7j47oxe7u6md2pbxr7uoanzgoemwravonro6srp5a2q at https://nftstorage.link/ipfs/bafkreib4hdjyxss7j47oxe7u6md2pbxr7uoanzgoemwravonro6srp5a2q
8-2adad64030caa55b.js:1 Uncaught (in promise) Error: Proof could not be found
    at ev (8-2adad64030caa55b.js:1:14317)
    at async Promise.all (index 0)
    at async f (8-2adad64030caa55b.js:1:14854)
```
