### ISSUE TITLE
Claim all fractions is broken

### ISSUE THREAD

**Issue by ryscheng** [hypercerts-org/hypercerts#601]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

SDK, Frontend Dapp

### To Reproduce

Try to claim all fractions from any allowlist created

### Describe the Bug

Gets stuck on "determining proofs"
with the following error message

```
verify-fraction-claim.ts:51 Uncaught (in promise) Error: Proof could not be found
    at verifyFractionClaim (verify-fraction-claim.ts:51:9)
    at async Promise.all (index 0)
    at async write (mintFractionAllowlistBatch.ts:59:21)
```

### Expected Behavior

Works

**Comment by ryscheng** [comment]
Hmm... Looks like we are grabbing the wrong value here
https://github.com/hypercerts-org/hypercerts/pull/542/files#diff-603946cc2a47ce9233623409af27242597b03a18f5c308566b381e05c7720278R32

we used to just parse `treeResponse`, but now we are parsing `treeResponse.value`, which is undefined.

**Comment by ryscheng** [comment]
https://github.com/hypercerts-org/hypercerts/pull/602
